#!/usr/bin/env python

import sys

# from rqt_virtual_joy.virtual_joy_module import VirtualJoy
from rqt_gui.main import Main


plugin = 'rqt_joy_monitor'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
